name: flutter_mjpeg
description: Flutter widget to show mjpeg stream from URL, mainly used by ip camera, stop itself when not on screen
version: 3.0.0
homepage: https://github.com/mylisabox/flutter_mjpeg

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  visibility_detector: ">=0.4.0+2"
  flutter_hooks: ">=0.20.3"
  http: ">=1.1.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
